version: "3.4"

services:
  app:
    container_name: game_of_life__app
    build:
      context: .
      dockerfile: ./src/Dockerfile
    image: ${IMAGE_APP}
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    restart: always
    volumes:
      - static_volume:/src/static/
      - media_volume:/src/media/
    logging:
      driver: json-file
    env_file:
      - .env
    command: bash -c "uvicorn app.internal.main:app --host 0.0.0.0 --port 8000"
volumes:
  static_volume:
  media_volume:
